const express = require('express');
const path = require('path');
const { db, DIRS } = require('../db');
const { authenticate } = require('../middleware/auth');

const router = express.Router();
// Media is fetched by <img>/<video>/<audio> tags which cannot send an
// Authorization header, so authenticate also accepts ?token=.
router.use(authenticate);

// Filenames are generated by the server and must match this exactly.
const SAFE_FILENAME = /^[a-zA-Z0-9._-]+$/;

function visible(user, row) {
  if (user.role === 'admin') return true;
  if (!row.is_private || row.released) return true;
  return user.role === 'author' && row.author_id === user.id;
}

/**
 * Defence in depth against path traversal:
 *  1. the filename comes from our own database, never from the URL,
 *  2. it must match a strict allow-list regex,
 *  3. the fully resolved path must still live inside the intended base dir,
 *  4. res.sendFile is given a root and a bare filename.
 */
function sendSafe(res, baseDir, filename, downloadName) {
  if (!filename || !SAFE_FILENAME.test(filename) || filename.includes('..')) {
    return res.status(400).json({ error: 'Invalid file reference.' });
  }
  const resolved = path.resolve(baseDir, filename);
  if (!resolved.startsWith(path.resolve(baseDir) + path.sep)) {
    return res.status(400).json({ error: 'Invalid file reference.' });
  }
  const options = {
    root: path.resolve(baseDir),
    acceptRanges: true, // lets video/audio seek via HTTP Range requests
    headers: downloadName
      ? { 'Content-Disposition': `attachment; filename="${downloadName.replace(/[^\w. ()-]/g, '_')}"` }
      : undefined,
  };
  res.sendFile(filename, options, (err) => {
    if (err && !res.headersSent) {
      res.status(404).json({ error: 'File not found on disk.' });
    }
  });
}

function loadContent(req, res) {
  const id = Number.parseInt(req.params.id, 10);
  if (!Number.isInteger(id)) {
    res.status(404).json({ error: 'Not found.' });
    return null;
  }
  const row = db.prepare('SELECT * FROM content WHERE id = ?').get(id);
  if (!row || !visible(req.user, row)) {
    res.status(404).json({ error: 'Not found.' });
    return null;
  }
  return row;
}

const DIR_BY_TYPE = { video: 'videos', audio: 'audio', file: 'files' };

// Main media stream / file body.
router.get('/:id/file', (req, res) => {
  const row = loadContent(req, res);
  if (!row) return;
  const dirKey = DIR_BY_TYPE[row.type];
  if (!dirKey || !row.filename) return res.status(404).json({ error: 'No file for this item.' });
  const download = req.query.download === 'true';
  sendSafe(res, DIRS[dirKey], row.filename, download ? row.original_name || row.filename : null);
});

// Thumbnail (video poster / audio waveform).
router.get('/:id/thumb', (req, res) => {
  const row = loadContent(req, res);
  if (!row) return;
  if (!row.thumbnail) return res.status(404).json({ error: 'No thumbnail yet.' });
  sendSafe(res, DIRS.thumbs, row.thumbnail, null);
});

// Animated GIF hover preview.
router.get('/:id/preview', (req, res) => {
  const row = loadContent(req, res);
  if (!row) return;
  if (!row.preview_gif) return res.status(404).json({ error: 'No preview yet.' });
  sendSafe(res, DIRS.previews, row.preview_gif, null);
});

module.exports = router;
